#' An artificial data set for logistic regression
#'
#' A data.frame with binary response and explanatory variables generated from multivariate normal distribution
#' \eqn{N(\boldsymbol{0}, \boldsymbol{\Sigma})}, where\eqn{\boldsymbol{\Sigma}_{ij}=0.5^{I(i\neq j)},
#' i,j=1,\dots,7.} The probability of the class label being 1 for a point \eqn{\boldsymbol{x}} is
#' \eqn{h(\boldsymbol{x}, \boldsymbol{\beta}) = 1/(1 + \exp(−\boldsymbol{x}^{T}\boldsymbol{\beta}))},
#' where \eqn{\boldsymbol{\beta}} is a 7 \eqn{\times} 1 vector of 0.5.
#'
#' @format ## `data_binary_class`
#' A data frame with 10000 rows and 7 columns:
#' \describe{
#'   \item{X1-X6}{explanatory variables generated from multivariate normal distribution}
#'   \item{y}{response variable}
#' }
"data_binary_class"

#' An artificial data set for linear regression.
#'
#' A data.frame with numeric response and explanatory variables simulated the real life borehole example
#' of the flow rate of water through a borehole from an upper aquifer to a lower aquifer separated by an
#' impermeable rock layer.
#'
#' @details
#' The response variable \eqn{\mathcal{Y}}, the flow rate through the borehole in \eqn{m^3 / yr},
#' is determined by a complex nonlinear function as follows,
#' \deqn{\mathcal{Y}=\frac{2 \pi T_{\mathrm{u}}\left(H_{\mathrm{u}}-H_{\mathrm{l}}\right)}{\ln \left(r / r_{\mathrm{w}}\right)\left[1+\frac{2 L T_{\mathrm{u}}}{\ln \left(r / r_{\mathrm{w}}\right) r_{\mathrm{w}}^2 K_{\mathrm{w}}^2}+\frac{T_{\mathrm{u}}}{T_1}\right]},}
#' where the 8 input variables with their usual input ranges are listed as follows:
#' * \eqn{r_{\mathrm{w}} \in[0.05,0.15]} means the radius of borehole (\eqn{m});
#' * \eqn{r \in[100,50000]} means the radius of influence (\eqn{m});
#' * \eqn{T_{\mathrm{u}} \in[63070,115600]} means the transmissivity of upper aquifer(\eqn{\left(\mathrm{m}^2 / \mathrm{yr}\right)});
#' * \eqn{T_1 \in[63.1,116]} means the transmissivity of lower aquifer(\eqn{\left(m^2 / y r\right)});
#' * \eqn{H_{\mathrm{u}} \in[990,1110]} means the potentiometric head of upper aquifer(\eqn{m});
#' * \eqn{H_1 \in [700,820]} means the potentiometric head of lower aquifer (\eqn{m});
#' * \eqn{L \in[1120,1680]} means the length of borehole (\eqn{m});
#' * \eqn{K_{\mathrm{w}} \in[9855,12045]} means the hydraulic conductivity of borehole (\eqn{m / y r}).
#'
#' The distribution of \eqn{r_{\mathrm{w}}} is the normal distribution\eqn{\mathcal{N}\left(0.10,0.0161812^2\right)},
#' the distribution of \eqn{r} is the lognormal distribution \eqn{\operatorname{Lognormal}\left(7.71,1.0056^2\right)},
#' and the distributions of other variables are all continuous uniform distribution on their corresponding domains.
#'
#' @format ## `data_numeric_regression`
#' A data frame with 10000 rows and 9 columns:
#' \describe{
#'   \item{\eqn{\mathcal{Y}}}{response variable, flow rate through the borehole.}
#'   \item{\eqn{r_{\mathrm{w}}}}{the radius of borehole.}
#'   \item{\eqn{r}}{the radius of influence.}
#'   \item{\eqn{T_{\mathrm{u}}}}{ the transmissivity of upper aquifer.}
#'   \item{\eqn{T_1}}{the transmissivity of lower aquifer.}
#'   \item{\eqn{H_{\mathrm{u}}}}{the potentiometric head of upper aquifer.}
#'   \item{\eqn{H_1}}{the potentiometric head of lower aquifer.}
#'   \item{\eqn{L}}{the length of borehole.}
#'   \item{\eqn{K_{\mathrm{w}}}}{the hydraulic conductivity of borehole.}
#' }
"data_numeric_regression"

#' Simulation datasets of IES Case1
#'
#' A data.frame with numeric response and real overall mean and three predictors generated from truncated multivariate normal distribution.
#'
#' @details
#'
#' The three predictors generated from truncated multivariate normal distribution
#' \eqn{TN(0, \Sigma, -2, 2)} , with mean zero and covariance matrix \eqn{\Sigma=(0.3^{\mathbb{1}(i \ne j)})} ,
#' and each predictor lies in \eqn{[-2, 2]}.
#'
#' The response are generated by \eqn{y = m(x) + \epsilon},  where
#' \deqn{\begin{aligned} m(x) &= m_1(x_1) + m_2(x_2) + m_3(x_3) \\
#'                            &= \frac{8}{4 + x_1} + \frac{\exp(3-x^2_2)}{4} + 1.5\sin(\frac{\pi}{2}x_3),
#'        \end{aligned}}
#' and \eqn{\epsilon} follows \eqn{N(0, \sigma^2)}, the variance is \eqn{\sigma^2=0.25}.
#'
#' We generated the above predictors using the `rtmvnorm` function in package `TruncatedNormal`.
#' @format
#' ## data_IES_Case_1_Train
#' A data.frame with 10000 rows and 5 columns.
#' \describe{
#'   \item{X1-X3}{Explanatory variables generated from truncated multivariate normal distribution.}
#'   \item{m}{Real overall average.}
#'   \item{y}{Response variable.}
#' }
"data_IES_Case_1_Train"

#' Simulation datasets of IES Case2
#'
#' A data.frame with numeric response and real overall mean and three predictors generated from truncated multivariate exponential distribution.
#'
#' @details
#'
#' The three predictors generated from truncated multivariate exponential distribution with
#' covariance matrix \eqn{\Sigma=(0.3^{\mathbb{1}(i \ne j)})}. The marginal distribution is exponential distribution
#' with rate 1, and is truncated by 4 and translated to \eqn{[-2, 2]}.
#'
#'
#' The response are generated by \eqn{y = m(x) + \epsilon},  where
#' \deqn{\begin{aligned} m(x) &= m_1(x_1) + m_2(x_2) + m_3(x_3) \\
#'                            &= \frac{8}{4 + x_1} + \frac{\exp(3-x^2_2)}{4} + 1.5\sin(\frac{\pi}{2}x_3),
#'        \end{aligned}}
#' and \eqn{\epsilon} follows \eqn{N(0, \sigma^2)}, the variance is \eqn{\sigma^2=0.25}.
#'
#' We generated the above predictors using the `ellipCopula` and `rCopula` function in package `copula`.
#'
#' @format
#' ## data_IES_Case_2_Train
#' A data.frame with 10000 rows and 5 columns.
#' \describe{
#'   \item{X1-X3}{Explanatory variables generated from truncated multivariate exponential distribution.}
#'   \item{m}{Real overall average.}
#'   \item{y}{Response variable.}
#' }
"data_IES_Case_2_Train"
