# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get subsample index of other column(except the first column) (IBOSS)
#'
#' @param r Subsample size of the column.
#' @param z A numeric vector. the column.
#' @param rdel Subsample index of the first column.
#' @return Subsample index of the column.
getIdxR_cpp <- function(r, z, rdel) {
    .Call(`_dbsubsampling_getIdxR_cpp`, r, z, rdel)
}

#' Get subsample index of the first column(IBOSS)
#'
#' @param r Subsample size of the first column.
#' @param z A numeric vector. the first column.
#' @return Subsample index of the first column.
getIdx_cpp <- function(r, z) {
    .Call(`_dbsubsampling_getIdx_cpp`, r, z)
}

#' Get L2 norm
#'
#' Get L2 norm of a matrix or data frame.
#'
#' @param X A matrix or data.frame.
#'
#' @return L2 norm of `X`(every row).
L2norm <- function(X) {
    .Call(`_dbsubsampling_L2norm`, X)
}

#' Find t smallest index of a vector
#'
#' @param loss A vector.
#' @param t A int.
#'
#' @return The index of the t smallest element of the vector.
bottom_t_index <- function(loss, t) {
    .Call(`_dbsubsampling_bottom_t_index`, loss, t)
}

#' Compute loss function for OSS
#'
#' @param candi The index of the candidate set.
#' @param last_index The index of the seleted point in last iteration.
#' @param X The whole data.
#' @param norm Norm of the whole data.
#'
#' @return Loss of every point in candidate set.
ComputeLoss <- function(candi, last_index, X, norm) {
    .Call(`_dbsubsampling_ComputeLoss`, candi, last_index, X, norm)
}

#' Rcpp version OSS (core code of `OSS`)
#'
#' @param X A matrix.
#' @param n Subsample size.
#'
#' @return Subsample index.
rcppOSS <- function(X, n) {
    .Call(`_dbsubsampling_rcppOSS`, X, n)
}

#' Find t smallest index of a vector (RcppArmadillo-version)
#'
#' @param x A vector.
#' @param k A int.
#'
#' @return The index of the t smallest element of the vector.
armabottom_k <- function(x, k) {
    .Call(`_dbsubsampling_armabottom_k`, x, k)
}

#' Scale a matrix (RcppArmadillo-version)
#'
#' @param X A matrix.
#'
#' @return Scaled matrix.
armaScaleMatrix <- function(X) {
    .Call(`_dbsubsampling_armaScaleMatrix`, X)
}

#' Compute loss function for OSS (RcppArmadillo-version)
#'
#' @param X Matrix of the candidate set.
#' @param xa Norm of the candidate set.
#' @param y A vector. The point which be selected last iteration.
#' @param ya Norm of `y`.
#' @param tPow The power of the loss function.
#'
#' @return Loss of the candidate set.
armaComputeLoss <- function(X, xa, y, ya, tPow) {
    .Call(`_dbsubsampling_armaComputeLoss`, X, xa, y, ya, tPow)
}

#' OSS (RcppArmadillo-version)
#' @param x A matrix.
#' @param k Subsample size.
#' @param tPow The power of the loss function.
#'
#' @return Subsample index.
armaOSS <- function(x, k, tPow = 2) {
    .Call(`_dbsubsampling_armaOSS`, x, k, tPow)
}

