# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getIdxR_cpp <- function(r, z, rdel) {
    .Call(`_dbsubsampling_getIdxR_cpp`, r, z, rdel)
}

getIdx_cpp <- function(r, z) {
    .Call(`_dbsubsampling_getIdx_cpp`, r, z)
}

